### ISSUE TITLE
Re-Run Job

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-server#107]
We want to be able to re-run Jobs, both at the Job and JobRequest levels.

#### Job
* Add a blue (primary) button to the right of the View button 
* Add a button in the tools section of the JobDetail page

Both buttons should duplicate the calling Job's JobRequest details (and make the first Job until job-runner can do that).

#### JobRequest
We don't currently have a detail page for JobRequests (we probably should), so we can only add a button on the list view.  However the show/hide jobs button is already quite large, so the UI needs some thought here.  However, when we _do_ find a good place for the control which activates it, we can duplicate the calling JobRequest.

---

Since we want both types of Re-Run Job to dupliate a JobRequest with either the original Job/action or a new one, we should be able to create a method on JobRequest with an optional `action_id` kwarg.

**Comment by sebbacon** [comment]
Additionally, I think a "re-run" job should be collapsed with all its previous runs. The common pattern during development is to keep re-trying the same thing with tweaks until it works. As a user, I don't want to see all the duplicates, just the most recent one, with a link (or similar) to list all the other duplicates. 

I think a perfectly good definition of "duplicate" is "JobRequest within the same workspace with the same `action_id`.  

Real-life illustration of how re-runs can become confusing noise:

![image](https://user-images.githubusercontent.com/211271/96426166-c9c8bb00-11f4-11eb-9c57-e2f122b9c45d.png)

**Comment by ghickman** [comment]
I think, for myself at least, thinking of Jobs as I think about runs in CI for my tests is going to help here.

Particularly seeing this screenshot, that looks a lot like how I get CI working every time I set it up, so a useful analogy/paradigm to design for!

> a "re-run" job should be collapsed with all its previous runs

With that in mind my first impression is that we should model this as JobRequest having a self-referential FK.  I'm not sure how we'll visually collapse this down as a mechanic but vaguely I think we want:
* Get leaf JobRequest
* Get chain of JobRequests
* Get Jobs of chained JobRequests, grouped owning JobRequest
* Order grouped Jobs by JobRequest creation date ASC
* Display only the leaf JobRequest in the list view but with all Jobs underneath

**Comment by sebbacon** [comment]
What, conceptually, does "chain of JobRequests" mean?

**Comment by ghickman** [comment]
Lets say you have `<JobRequest (1)>` which fails so you click/tap "Rerun Job".  We're going to create a new `JobRequest` (`<JobRequest (2)>`), copied from the first and set it's `parent` FK to the first so we know where it came from (more on that in a minute).  Now lets say you end up in the same situation as above (N re-runs of a Job because Reasons™).

That means we're going to end up with a "chain" of `<JobRequest (1)> -> <JobRequest (2)> -> … <JobRequest (N)>` built via each `JobRequest.parent`.

By default that would mean that one could Rerun a JobRequest at any point in the "chain" but I don't think that concept has any meaning for us since we're always going to want to run the latest version of a research project (at least for the foreseeable future I think?) so I'll probably make any logic go "find the end of this chain and copy from that).

**Comment by sebbacon** [comment]
I think this is now superceded by the current pipeline-centered UI which collapses your default view to be "most recent status of action", thus the re-run semantics are, to the user, identical to the run semantics, except you're clicking "run" against an action in a currenlty-successful state
