### ISSUE TITLE
API URL Field Can't Look up PK

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-server#112]
[Sentry](https://sentry.io/organizations/ebm-datalab/issues/1961704931/?project=5443358&query=is%3Aunresolved)

The `/api/jobs` endpoint is 500ing because it's trying to look up `.pk` on an empty string when constructing the `workspace.url` key.  This is likely due to a legacy Job having no `job_request`.

@sebbacon – do we need to include the `url` in the API? (or even the `workspace` key?)

**Comment by sebbacon** [comment]
It's really just there because it was handy in the DRF web ui when that was the only UI we had

**Comment by ghickman** [comment]
Removed the `workspace` key in #116 to fix this.
