### ISSUE TITLE
By default, filter workspaces and jobs to current user

### ISSUE THREAD

**Issue by sebbacon** [opensafely/job-server#117]
As a study developer, when I am working on a study, I tend to spend a lot of time within a particular workspace, which I created, adding and re-running jobs.

I think this means we want the concept of "workspace" to be more central and more sticky.

When I first log in, by default, I want to see my own jobs and workspaces, not those of other people.

**Comment by ghickman** [comment]
Do you think Workspaces are a little like Users/Orgs on sites like GitHub?  Eg should we adopt something along the lines of `<domain>/workspace-slug/<other url bits>`?

Either way I think we need `/` to stop redirecting to `/jobs/` (as I expected it would eventually) and create a logged-in-user centric "Dashboard".  For now this can be the jobs list page (even reusing the template) with the User filter removed and always filtered to the current User.

**Comment by sebbacon** [comment]
`<domain>/workspace-slug/<other url bits>` <- I think so

**Comment by ghickman** [comment]
Now that #216 is in, this is partially done, partially defunct.
