### ISSUE TITLE
Somewhat formless thoughts on how everything is structured

### ISSUE THREAD

**Issue by evansd** [opensafely/job-server#129]
Copied from Slack
-------------------
@ghickman  @sebbacon  Apologies in advance for this but ...
I'm just having a rethink about the job runner and server and how they should fit together.
This is working backwards from what the most helpful UI would be which (as I think we've already discussed) would probably be something like a list of all project actions with the latest status for each action and the ability to select specific actions to run or re-run.
So what if:
 * A single JobRequest could be for a list of actions, rather than just one action.
 * The job-runner would only ever run actions it was explicitly asked to, with no automatic dependency running.
 * The job-runner would still do dependency resolution to determine whether an action can be run at all, and to determine what order to run them in.
 * Rather than just syncing up the state of currently active Jobs, the job-runner would sync the latest state for every action in the workspace of each currently active JobRequest. That way the job-server should be able to maintain an accurate view of the current state of the workspace.

**Comment by ghickman** [comment]
I mostly want to clear up some specifics before I think too deeply on this just to make sure we're on the same page with what you're saying!

> what the most helpful UI would be

Which part of the job-server UI do you mean here?  Requesting an Action is run?

> A single JobRequest could be for a list of actions, rather than just one action.

What does this solve for?  I'm not particularly familiar with any actions workflow other than "run them all, then re run the failing ones until it all completes", do you have examples of any others?

> The job-runner would still do dependency resolution to determine whether an action can be run at all, and to determine what order to run them in.

I think this implies that the job-server also needs to do dependency resolution, such that neither is the definitive Source of Truth any more?

> Rather than just syncing up the state of currently active Jobs, the job-runner would sync the latest state for every action in the workspace of each currently active JobRequest.

I'm not sure how this differs from what we discussed in #84?  I believe the plan was to POST a payload of JobRequest-with-its-Jobs each time one of those Job's changed state
---

It reads to me like there's two take-aways from this idea (please correct me if I'm wrong!):
* How we request Jobs could be better tailored to how we use the runner.
* We could make the runner-to-server sync faster/more efficient.

**Comment by evansd** [comment]
> Which part of the job-server UI do you mean here?  Requesting an Action is run?

I think I mean the primary bit of the UI that the researchers interact with, once they've navigated to the workspace. It would be the place where they can see what's currently running, what's succeeded and failed, and from which they can kick off new jobs.

So rather a list of JobRequests or Jobs as the primary view, they can think in terms of "what's the overall state of my project?".

---
> What does this solve for?  I'm not particularly familiar with any actions workflow other than "run them all, then re run the failing ones until it all completes", do you have examples of any others?

Examples might be: re-run this job and all the jobs which depend on its output; re-run everything except the cohort extraction because that takes ages and it hasn't changed. The general point would be that it would be better if we could discover these workflows and support them in the interface without building them in to our data structures.

Maybe we don't need actually need to make this change though. The job-server could just create multiple JobRequests. It would just need to make sure it creates them in the right order i.e. dependencies first. But it's going to have to do dependency resolution anyway so that should be fine.

---
> I think this implies that the job-server also needs to do dependency resolution, such that neither is the definitive Source of Truth any more?

I'd say the definitive source of truth is the `project.yaml` file and as long as we're passing specific commits around then there's no possibility of either side disagreeing about what the contents of that file is.

The most likely form of disagreement would be the job-server thinking that an action has run successfully but those files being deleted from the job-runner. If that's the case then the requested jobs would fail (because a dependency hadn't actually been run) and the job-server would have its state corrected by the job-runner on the next poll.

---
> I'm not sure how this differs from what we discussed in #84? I believe the plan was to POST a payload of JobRequest-with-its-Jobs each time one of those Job's changed state

It's not _very_ different but it is a bit different. The difference is that job-runner will tell job-server about the state of e.g. the `generate_cohort` action even if that wasn't one of the jobs associated with the JobRequest. This is to avoid the issue just referred to above whether job-server and job-runner disagree about what jobs have been successfully run.

---
> It reads to me like there's two take-aways from this idea (please correct me if I'm wrong!)

I wasn't thinking about efficiency at all here really. If anything this is a bit less efficient as it involves transferring the state of every action in a workspace, not just the newly requested ones.

The main considerations for me were: what kind of UI would most make sense to someone new to this whole thing and how can we support that? And how can we avoid baking assumptions about workflow into the way the system in architected.

**Comment by sebbacon** [comment]
Generally makes sense.

So the only change in the job-server initially would be that the gesture of requesting a new `run_all` job means the system creating all the dependencies itself -- based on `project.yaml` and the current database state?  This means the very existence of a job *implies* the `force_run` flag has been set?

If there is no current database state (i.e. it's been deleted), that means all the dependency jobs would be created. How would the user communicate "don't re-run if there's already an output"?

**Comment by evansd** [comment]
My brain is starting to hurt a bit, but I can't quite drop this. Here's where I think I'm going with this.

1. The UI we really want is a sort of GUI over Make i.e. here are a bunch of actions you can run to produce files, with various dependencies between them; show me what's already run/is running and let me choose what actions to take.

2. What makes this complicated is that it involves a distributed system where communication can only be initiated in one direction.

3. What makes it even more complicated is that state can be modified on one system through a process completely external to the system. By which I mean, files can be deleted without this being done via the job-runner. So the job-server can never be sure it has an accurate view of the state of the system.

4. We've attempted to deal with this by taking some of the decisions about what should be run (which I think ultimately should be made by the user) and delegating them to the job-runner on the basis that it's the system that knows what files exist.

5. But this adds complexity because there's now no longer a direct correspondence between what you asked the job-runner to do and what it's doing. And it also restricts the kind of UI we can offer because we have to think in advance what sort of workflows the user might want to do and communicate the _workflow itself_ (force run, force run dependencies, force run dependents etc) rather than just the list of actions the user wants.

6. So I'm trying to think of ways we can put control back in the hands of the job-server while dealing with the inconsistent state problem.

Maybe there's mileage in having the job-server include with every JobRequest a list of what it thinks are all the successfully completed actions in a workspace. If the job-runner doesn't agree then it rejects the JobRequest (creates a failed Job or something) and POSTs the entire state of the workspace back to the job-server.

**Comment by evansd** [comment]
Right, anyway. I'd hoped some ah ha moment of clarity would arise from me writing all this down but it hasn't. We've got a plan already, it might not be perfect but it's a good one. Let's stick to it. It's all just code, we can change it down the line if we get a better idea.

**Comment by ghickman** [comment]
> We've got a plan already

Agreed, but as you said nothing is perfect!

I think we should definitely revisit your idea of exposing dependencies and their state for (workspace, project.yaml-sha).  That feels very related to the UX we're trying to provide with re-running jobs in #107, specifically around reducing clicks a User has to make to kick off the actions they want.

**Comment by sebbacon** [comment]
For the record, I have just hit [a real-life use-case](https://github.com/opensafely/school-age-children-and-covid/issues/60#issuecomment-713370260) which I always knew would come up at some point. Harriet has rewritten some stata in one script that depends on the output of another script which she's also rewritten.

At the moment, we only have "force-run this action" and "force-run this action and all its dependencies". I want either "force-run this action and all its dependents", or "force-run this action and this dependent" in a single gesture (this could just be a form which lists all the actions and I tick the ones I want)
