### ISSUE TITLE
Suggested action-running-re-running UI

### ISSUE THREAD

**Issue by sebbacon** [opensafely/job-server#133]
Based on the discussion in #129, here is a straw man suggestion: 

```yaml
actions:
  generate_cohort: 
  massage_data:
    needs: [generate_cohort]
  report:
    needs: [massage_data]
  draw_histogram:
    needs: [massage_data]
  run_all:
    needs: [draw_histogram, report]
```

This would in the first iteration produce checkboxes in a table (perhaps we don't even need col 2, but I think we probably do):

| action | needs | last_status |
|----------|----------|----|
| [ ] generate_cohort | *nothing* | never_run |
| [ ] massage_data | generate_cohort |never_run|
|[ ] report |massage_data|never_run|
|[ ] draw_histogram |massage_data|never_run|
|[ ] run_all| *everything*|never_run|
`[submit selected jobs]`

The users wants to run everything for the first time.
They tick `run_all`. Everything else is ticked for them. They submit the form.  It looks something like this:

| action | needs | last_status |
|----------|----------|----|
| [ ] generate_cohort | *nothing* | running |
| [ ] massage_data | generate_cohort |pending|
|[ ] report |massage_data|pending|
|[ ] draw_histogram |massage_data|pending|
|[ ] run_all| *everything*|pending|
`[submit selected jobs]` `[cancel selected jobs]`

After a while, everything completes. The histogram had an error, visible in the status column:

| action | needs | last_status |
|----------|----------|----|
| [ ] generate_cohort | *nothing* | success |
| [ ] massage_data | generate_cohort |success|
|[ ] report |massage_data|success|
|[ ] draw_histogram |massage_data|error|
|[ ] run_all| *everything*|success|
`[select failed jobs]` 
`[submit selected jobs]` 

The users edits and commits the script, and then clicks `run_all`. All the checkboxes are ticked, including the actions which were previously successful. The system will interpret this as a "force run" in those cases, and alerts the user to this fact next to the submit button.  The user realises they just want to re-run the failed action. They use the "select failed jobs" and submit the form. It all works:

| action | needs | last_status |
|----------|----------|----|
| [ ] generate_cohort | *nothing* | success |
| [ ] massage_data | generate_cohort |success|
|[ ] report |massage_data|success|
|[ ] draw_histogram |massage_data|success|
|[ ] run_all| *everything*|success|
`[submit selected jobs]` 

The user realises they forgot something in the `massage_data` script, although the script didn't fail.  They select the tickbox next to it. Because this was a `success` last time, the notification alerts them to this. The form also prompts the user if they also want to select `draw_histogram` on the grounds it is a dependent. The user agrees; the two actions are ticked, and the user submits the form

**Comment by ghickman** [comment]
In the final example, what happens when the User doesn't select `draw_histogram` and only submits the `massage_data` Action?
