### ISSUE TITLE
There should be a way to see untruncated action_id

### ISSUE THREAD

**Issue by sebbacon** [opensafely/job-server#138]
[This project has lots of actions starting with the same characters](https://github.com/opensafely/school-age-children-and-covid/blob/69ef0362160201accd7b8d65c45326dc24d367b7/project.yaml#L140-L163), which makes the job listing page a bit useless:

![image](https://user-images.githubusercontent.com/211271/96965905-dc990380-1504-11eb-9463-db2ada86beed.png)

Perhaps the tooltip (or other hover state) should be the untruncated version?

**Comment by ghickman** [comment]
There should already be a title, that's a bug, sorry!

I think, related to this, we should also have a detail page for a `JobRequest`, listing all the Jobs and linking off to a Workspace so we can fully expand various bits of data.  Probably more usable for the tech team, but also while we're building it out it'll proably be useful for debugging.

**Comment by ghickman** [comment]
JobDetail page added in #159 and title added in #151
