### ISSUE TITLE
Add server health checks

### ISSUE THREAD

**Issue by sebbacon** [opensafely/job-server#146]
To give people comfort that the server is running, perhaps in a little status bar / box at the top, we could add:

* queue size stats (unacked, started)
* date of most recent ack

We could add an alert icon there which appears if the unacked queue size > 0 and the date of most recent ack > 5 mins ago?

There are various other ideas we've had where the server can include health status in its posts, but I think this is the lowest-ceremony useful thing?

**Comment by ghickman** [comment]
(mostly for me when I get to this)

We can use a middleware to track the latest API request time, probably in some kind of stats db table for now as it's low traffic.

Queue sizes should be easier enough to generate with queries against `JobRequest`.

Stats will need to be generated in a context processor.
