### ISSUE TITLE
Use Pagination with GitHub's GraphQL API

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-server#149]
When adding #143 I couldn't see how to easily paginate the `repositories` part of the call.  GitHub limits us to 100 repositories in that call and the Researchers Team has 58 repos currently.

[Pagination in GraphQL](https://graphql.github.io/learn/pagination/) is done with cursors.

Some initial questions, mostly based on GitHub's REST API:
* How do we know when we've exhausted a resources pages?
* How to track a cursor?
* Can we create a generator function which yields single Repo, Branches pairs?

**Comment by sebbacon** [comment]
Closed for #250

**Comment by ghickman** [comment]
Pagination of the GraphQL API is not the same as paginating the UI component!  We're currently consuming the first 100 repos from the Research team, when the number of repos in that team ticks to 101, we'll be missing a repo to select from.

This is unrelated to listing Workspaces on the home page.

**Comment by sebbacon** [comment]
So is this *anywhere* we list Workspaces?

**Comment by ghickman** [comment]
Nope, it's entirely unrelated to **listing** Workspaces!

On the **create** Workspace page we call the GraphQL to populate the repo & branch dropdowns:

![](https://p198.p4.n0.cdn.getcloudapp.com/items/GGu2Nr5j/Image%202020-12-03%20at%209.08.38%20am.jpg?v=abf9a3eab993d391fa66f6ec9935a6fc)

We're up to 72 repositories (according to [here](https://github.com/orgs/opensafely/teams/researchers/repositories)), which is getting a bit close to the cut off, next month might be a good time to work on this?
