### ISSUE TITLE
JobRequest Detail Page

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-server#153]
Just like Workspace and Job both have detail pages we should have a JobRequest detail page.

As a start it should include:
* JobRequest instance details (with links to relevant linked models)
* List related Jobs with filters

Later on we can think about:
* An event log
* Re-running one/all Jobs (#107)
* Re-running the JobRequest
* Start/Stop etc

**Comment by sebbacon** [comment]
I am not sure that the abstraction of a JobRequest is particularly meaningful at all to the end user. For them, isn't it just "I requested these 3 jobs at the same time"?

If so, then I think the only way we need to surface them in the UI is with a visual hint in the master log that "this job was run as part of a group". Perhaps always ordering logs by jobrequest-then-job and drawing a box around them?

**Comment by ghickman** [comment]
For the end user, probably not, although potentially some use in being able to point one of us at a particular request.  However, we've not seen that as a use case yet so potentially YAGNI.

For us as a debug tool?  Definitely useful!  This page already exists, but I'd left the issue open because I don't like how we have to navigate to it currently (workspace logs -> view Job -> view JobRequest).  We track things like the SHA Jobs are working from and whether force_run_dependencies was set there.  In debugging previous problems the page has been useful to check what we were expecting the job-runner to work from.

**Comment by sebbacon** [comment]
OK, maybe close this issue and open a new one for the specific thing you want to do?

**Comment by ghickman** [comment]
Done in #253
