### ISSUE TITLE
[Un]Acked State

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-server#164]
What do we think marks a Job as `acked` on job-server currently?

I know we previously talked about a JobRequest having Jobs (since job-runner will create them) as a way to identify that.  However we're not there and job-server currently creates 1 Job per requested Action.

I'm happy to add a BooleanField in the interm, just wanted to check I hadn't overlooked something!

cc @sebbacon @evansd @bloodearnest

**Comment by evansd** [comment]
I _think_ this is what the `started` field actually means. If you look here:
https://github.com/opensafely/job-runner/blob/3e7806eb07a7fa9c587db1bb014f713827241a20/jobrunner/main.py#L177-L179

You'll see if sets `started` immediately on receiving the job, not when it actually starts running it which I think is what the `started_at` timestamp indicates.

**Comment by sebbacon** [comment]
Right. `started` gets unset if a dependency is running, so it can get re-acked later... so it's slightly overloaded in that sense.

**Comment by ghickman** [comment]
That's good enough for my needs in #123 , thanks both!
