### ISSUE TITLE
Extra Jobs Being Generated

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-server#197]
For [`JobRequest#187`](https://jobs.opensafely.org/job-requests/187/) the `run_all` action was selected.

The `project.yaml` for the SHA that `JobRequest` is working from defines 8 actions (including `run_all`).

However, we've generated 14 `Job`s.  Based on when they were created it looks like `Job`s 664-669 are the duplicates.

cc @wjchulme @evansd

**Comment by ghickman** [comment]
I've created `os-demo-research.log` on the server which should be only logs created for this `JobRequest` since I rebooted job-runner right before it started and nothing has run since.

Unfortunately it's 65K lines long.

**Comment by ghickman** [comment]
`664` is the first duplicate Job (`generate_cohort_activity`).

The logs show these Jobs creating it:
* `656` (`run_all`)
* `659` (`plot_activity`)
* `658` (`generate_measures_activity`)
* `667` (`generate_measures_activity`) -> dupe!

`667` is also a duplicate, but only these Jobs [correctly] create it:
* `656` (`run_all`)
* `659` (`plot_activity`)

**Comment by ghickman** [comment]
Happened again with [`JobRequest#262`](https://jobs.opensafely.org/job-requests/262/) on carehomes.

54 Jobs have been generated from 11 actions.

**Comment by ghickman** [comment]
The [project.yaml](https://github.com/opensafely/carehomes-research/blob/46ba6d026c5fcaf21efb168009b154470141b62a/project.yaml) defintes 11 actions.

If you go through each of those 11 actions counting the number of actions passed while traversing to the route you get 43, add on the 11 actions we should actually be running and you get 54.  This seems too exact to be coincidence 🤔

**Comment by ghickman** [comment]
I've done some further digging and while I don't have answers yet, I've got some more ideas at least.

#### Context
Some context first, particularly around `JobRequest` and `Job` creation.  When a User [creates a `JobRequest` via the UI](https://github.com/opensafely/job-server/blob/master/jobserver/views.py#L256-L260) we create an instance tracking the `force_run_dependencies` option and which Actions were requested.  We then **also** create a `Job` for each of the `requested_actions`, setting `force=True`.  The dependent `Job`s are **created by job-runner**.

The API hides the existance of `JobRequests`, pulling relevant fields onto the `Job` records for job-runner to consume.

In [`JobRequest#262`](https://jobs.opensafely.org/job-requests/262/) `force_run_dependencies` has been set, and *all* its `Job`s have `force_run` set.

#### Hypothesis
Looking at the logs for the [previous JobRequest this happened for](https://jobs.opensafely.org/job-requests/187/) it looked like, but I couldn't confirm, that the requested Action and it's dependencies would run as expected (passing or failing) then all the duplicates would start popping up.

My guess, which I've not managed to confirm yet, is that there is some interaction which means each Action is recursively having their dependency tree turned into new `Job`s.

For example, in carehomes there's an Action called `descriptive` which first pops up as [`Job#777`](https://jobs.opensafely.org/jobs/777/) since it's the last dependency of `run_all` (the requested action).  It has the dependencies `data_setup`, which has the dependencies `generate_cohort` and `calc_coverage`, with `calc_coverage` having the dependency `generate_cohort_coverage`.  One could expect these to run in the order:
1. `generate_cohort_coverage`
1. `calc_coverage`
1. `generate_cohort`
1. `data_check`

and we have Jobs in that order right after `descriptive`! ([`Job#778`](https://jobs.opensafely.org/jobs/778/), [`Job#779`](https://jobs.opensafely.org/jobs/779/), [`Job#780`](https://jobs.opensafely.org/jobs/780/), [`Job#781`](https://jobs.opensafely.org/jobs/781/))

#### Replication
I've pulled a copy of the production database and "rolled it back" by doing:
1. remove all `Job`s after `768` (the one job-server created) (`delete from jobserver_job where id > 768;`).
1. remove all `JobRequest`s after `262` (`delete from jobserver_jobrequest where id > 262;`).
1. Reset all the relevant fields on `Job#768` (`update jobserver_job set status_code = NULL, status_message = '', started = false, started_at = NULL, completed_at = NULL where id = 768;`).

This brings the database back to the point where [`JobRequest#262`](https://jobs.opensafely.org/job-requests/262/) had been created but job-runner had not acked ([`Job#768`](https://jobs.opensafely.org/jobs/777/)).

Next I want to run job-runner locally to investigate the `job_spec` state as it passes through `server_interaction.start_dependent_job_or_raise_if_unfinished()` since this is where the logic to create further `Job`s exists.

**Comment by sebbacon** [comment]
> For example, in carehomes there's an Action called `descriptive` which first pops up as Job#777 since it's the last dependency of run_all (the requested action) ... and we have Jobs in that order right after `descriptive`!

I don't follow what the hypothesis is -- isn't this exactly what we *would* expect as these are all upstream of `run_all`?

**Comment by sebbacon** [comment]
But yes, it sounds like each action is getting itself and all its dependencies run.

So calling `A` in a tree `A -> B -> C` results in `A, B, C`, `B,C`, and `C` being run

I wonder if this is an untested interaction with `force_run_dependencies`.  

The big question is if this is worth fulling unwinding and fixing, given we tentatively think Dave's rewrite is nearly ready.

Is there a workaround? For example, we think `run_all` works when *not* in force_run mode, so we could just delete / archive old jobs when a user wants to do a fresh run.

Or we could tell users to individually run actions.

It all depends somewhat on ETA for the new version.

**Comment by ghickman** [comment]
> isn't this exactly what we would expect as these are all upstream of run_all

I wasn't expecting (even with `force_run` and `force_run_dependencies`) to see, for example, 20 `generate_cohort_coverage` Jobs generated from selecting `run_all`!  Is that the expected flow though?

**Comment by ghickman** [comment]
> Or we could tell users to individually run actions.

Would testing this with `carehomes` be disruptive to the researchers?  The first time we saw this it was in the `os-measures-demo` workspace which is possibly less disruptive to test with?

**Comment by sebbacon** [comment]
Emily can't really do anything with carehomes at the moment anyway; if in the process of testing it we generate fresh outputs for each step that is a great bonus!

**Comment by sebbacon** [comment]
Though see conversations in Slack about not being able to `git clone` it at the moment.... so `os-measures-demo` may be better in that regard (if/until @evansd deploys a git fix)

**Comment by sebbacon** [comment]
I assume this is not happening any more? Can we run a test to check, and close if so?

**Comment by ghickman** [comment]
We've not seen this pop up since the v2 deploy so I'll close for now.  If it pops up again we can re-investigate.
