### ISSUE TITLE
Workspace Uniqueness

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-server#202]
Workspace currently has no uniqueness constraints on it.

Would `("repo", "branch")` make sense as a unique combo?

cc @evansd @sebbacon

**Comment by evansd** [comment]
I don't think we necessarily want to enforce that. At a minimum we'd want to also include database. But I think it's better not to preempt how people will want to use workspaces.

The thing I have wondered about is having a unique slug for each workspace. The create workspace form could autogenerate a sensible default for this (repo-name-branch or something) but let the user customise it. It would mean we could drop the workspace ID from the output directory name, which makes it slightly more friendly and readable.

**Comment by ghickman** [comment]
With the changes in #199 we make use of `Workspace.name` around the site.  [Currently](https://jobs.opensafely.org/workspaces/) those all look like slugs.

What about making names unique and enforcing they're slugs?

**Comment by evansd** [comment]
Perfect, from my point of view. I think there might be a bit of UX work around making sure name is the last field in the form and auto-populating a sensible default, but nothing too difficult.
