### ISSUE TITLE
include commit info when viewing jobs

### ISSUE THREAD

**Issue by wjchulme** [opensafely/job-server#211]
Can we include a link to the exact version/commit of the repo on which each job was run?

If I run action 1 using commit `abc1`, then update the repo, and run action 2 on commit `abc2`, it would be useful to be able to see clearly that the outputs from each of those jobs are based on different commits. So just an extra line eg [here](http://jobs.opensafely.org/jobs/732/) with a link to the commit. 

Ideally this shouldn't happen (or perhaps even shouldn't be possible without some gaurantee that the outputs won't differ between commits). But since it can, I want to be able to know about it.

**Comment by evansd** [comment]
:+1: You're exactly right. This is solved already in the new job-server/job-runner combo.

**Comment by ghickman** [comment]
@wjchulme – even better, it's already implemented but slightly hidden (which is a bug in of itself!).  If you click on the Request you'll get two buttons on the right "View Repo" and "View project.yaml" both of which are linked to the SHA the Request is tied to.

**Comment by sebbacon** [comment]
Is it already surfaced in the job server UI though? (i.e. does this ticket need to stay open?)

**Comment by wjchulme** [comment]
Ah no it's there. great! happy to keep it closed. I'll leave it to you @ghickman if you want to make it more obvious.
