### ISSUE TITLE
Notify users by email when a job has finished

### ISSUE THREAD

**Issue by wjchulme** [opensafely/job-server#214]
as a default=no option

**Comment by ghickman** [comment]
We're pulling email addresses from GitHub when Users authenticate, is that a good enough first pass for you?

**Comment by wjchulme** [comment]
yep, that's what I expected

**Comment by sebbacon** [comment]
Would the setting be per-user (notify me of everything), per-workspace, per-job or per-jobrequest (i.e. group of jobs requested at the same time)? Would it be one email per job, or per jobrequest?

My preference is per-workspace setting, and for individual emails for each job as it's easier for us to implement and explain; it's then up to the user to set up email filters as they like.  There should be a help message explaining that it could result in a lot of emails and they should consider filtering them in their email client.  There should be a "turn on/off notifications" link on the main action-running user interface for a workspace.

Subject could be

     [os <workspace-name>] <action> <succeeded|failed>

Content could be

```
<action> in workspace <workspace> <succeed|failed> after <elapsed time> with the following message:

<message>
```

This could be HTML email where `<workspace>` and `<succeeded|failed>` are URLs

**Comment by HelenCEBM** [comment]
It would be quite useful to know when a job has started (i.e. after queuing) as well, so that if you already know how long it takes to run you get an idea of when it might finish a bit more in advance.
