### ISSUE TITLE
Each backend should use token-based auth

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-server#222]
We currently use HTTP Basic Auth to authenticate job-runner for API usage.  This is tied to a User instance.  This works fine as an authentication method, but has some other downsides.

We have to remember to exclude that User when making changes to Human Users.  We will likely add successive Users for each backend.

I propose we switch to Token based auth, using the standard `Authorization` HTTP header, and tying the Token to a new `Backend` instance.  This would add a few benefits:
* API responses are now tied to the authenticating token's Backend.
* Stats gathering can be tied to the Backend (it's currently global to the API prefix).

@sebbacon @evansd @bloodearnest thoughts?

**Comment by evansd** [comment]
As long as it's just "stick this magic string in a header" from the job-runner's point of view then it's fine by me :)

**Comment by ghickman** [comment]
@evansd it would be exactly that 👍

**Comment by ghickman** [comment]
Backend-based auth and per-backend stats are now deployed.
