### ISSUE TITLE
Live-update job statuses on workspace detail page

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-server#248]
WorkspaceDetail is expected to be our core page for a given Workspace, however it doesn't update so the statuses on there can get out of date.

A fairly simple solution is some javascript which polls an API endpoint to get statuses for the given workspace and updates the frontend.

**Comment by evansd** [comment]
I wrote a thing once which was the absolute crudest live updating page system you could imagine but it worked surprisingly well. It was a a few lines of jQuery, which reloaded the entire page in an XHR request and then pulled out specific elements from the response and replaced the matching elements on the page with the new versions.

You used it by setting a `data-refresh-in="<seconds>"` attribute to any element you wanted to update. Combined with liberal use of font-awesome spinners it gave the whole thing a very dynamic feel while involving almost no custom JS at all.

Happy to share if you're interested.

**Comment by ghickman** [comment]
Ha, love it.  I did something similar with `<meta http-equiv="refresh" content="5">` recently!

I considered doing the same this time but the WorkspaceDetail page makes a request to GitHub's API to get the project.yaml and I'm not sure I want to incur that time penalty on every update.  I need to do some testing to see how bad it is in practice really!

**Comment by evansd** [comment]
Ah, very good point. Yes, this probably does call for something a bit more sophisticated then :)
