### ISSUE TITLE
Do we still need Job.needed_by?

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-server#266]
Previously we used this field to store the information required to build a dependency tree.  However, the only place we show dependencies currently is on the JobRequest creation form, which is driven by the `project.yaml` we download on page load:

![](https://p198.p4.n0.cdn.getcloudapp.com/items/JruqL9go/Image%202020-12-07%20at%2010.51.13%20am.jpg?v=bb157af0ee1c5aeb390fe9d82e990db9)

The v2 API does not provide needed_by data currently, and I'm wondering if we actually need it?

@sebbacon @bloodearnest @evansd – Would this be useful in debugging?

@sebbacon – did you have future plans for dependency visualisation?

**Comment by evansd** [comment]
If needed, job-runner can supply a list of the other jobs each job is waiting on via the API. I'd say remove it for now, even if we do decide to add something similar further down the line.
