### ISSUE TITLE
Think about formatting of status_message

### ISSUE THREAD

**Issue by evansd** [opensafely/job-server#271]
`status_message` strings contain some structured formatting (newlines and spaces) that would benefit from wrapping in a `<pre>` block. e.g. compare the current view:

![jobs opensafely org_jobs_wznuq3e5pj7lsn56_ (1)](https://user-images.githubusercontent.com/19630/101483454-15bff280-3950-11eb-8d37-99ef0370ae7b.png)

with:

![jobs opensafely org_jobs_wznuq3e5pj7lsn56_](https://user-images.githubusercontent.com/19630/101483458-1789b600-3950-11eb-9397-e50d4614d993.png)

That's just sticking `<pre>` tags around the `<code>` tags which doesn't quite look right but hopefully you can see where I'm going with this.

**Comment by ghickman** [comment]
v2 continuing to bring really nice features 🎉
