### ISSUE TITLE
Explain `run_all` behaviour in words on the workspace page

### ISSUE THREAD

**Issue by sebbacon** [opensafely/job-server#276]
I'm sure we'll be changing the behaviour to make it more intuitive at some point, but until then, we need text explaining

* clicking `run` on a previously-successful, previously-failed or never-run action will always run it
* `run_all` is a special action that runs everything *unless it's successfully run before* in which case it skips re-running that *unless it failed* in which case `run_all` refuses to run. Unless you click "force run all dependencies"

I leave the challenge of finding a better wording for bullet point 2 to you :P

**Comment by ghickman** [comment]
> unless it's successfully run before

Is that true now `force` is implied by clicking a button? (cc @evansd)

**Comment by evansd** [comment]
Yes, any explicitly requested actions (i.e ones you've clicked buttons for) always attempt to run, whether or not they've previously succeeded or failed.

And yes, sadly, I think Seb's bullet point 2 is accurate!

**Comment by sebbacon** [comment]
Makes me wonder if "run_all" should only be provided as an option if _none_ of the jobs have ever been run before? That'd clear things up a bit..?!
