### ISSUE TITLE
Expose "Missing Branch"

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-server#314]
When the branch for a Workspace is deleted on GitHub we show the user "Could not find project.yaml" as the error message.  While technically correct we can probably expose a _bit_ more information as to why that might be the case.

Let's try and expose the fact that a branch no longer exists.  I would expect the GitHub API to tell us this in some way, but it might require an extra API call to do so.

**Comment by HelenCEBM** [comment]
I think the explanatory/reassuring text I was looking for is something like: "if you want to run actions in this workspace, please fix the error above. If the branch no longer exists this may not be possible, but you can set up a new workspace to run actions in this repository, or view the logs for this workspace using the button above" (improvements to this wording welcome!!)
