### ISSUE TITLE
Intermittent Backend Error

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-server#332]
Both Helen and I have seen an error banner right after submitting a JobRequest, which seems to go away shortly afterwards.

Potentially related was an odd log line @bloodearnest saw in the job-runner logs where a failure was logged:

```
sync JobRequest failed:
 ref=njsrrj333mdazbqr
```

**Comment by ghickman** [comment]
Helen mentioned it went away for her on a refresh - could this be template variable overloading after a submitted job?

**Comment by evansd** [comment]
Copying from Slack as it's probably more useful here:

> Just from a brief look at the code, it seems that if there are no un-acked jobs then it skips the warning banner logic. So I think what might be happening is that we're seeing the warning banner for the brief interval before the job is acknowledged
> 
> That suggests to me there might something wrong in the rest of the logic for displaying the warning banner, and it's just that it's usually hidden because there are no un-acked jobs
> 
> I also wonder if the check should be that there are no active jobs, rather than un-acked ones. If there are jobs still running and the job-runner is failing to connect then it won't be updating their state correctly and that seems worth surfacing to the user

**Comment by evansd** [comment]
Here's the relevant code that gave me pause:
https://github.com/opensafely/job-server/blob/e8c2b7b249885c606ba00b7806a037f83986cea2/jobserver/backends.py#L32-L44

**Comment by ghickman** [comment]
@evansd – yep, all good points!  I suspect our logic around "is the backend still up" has subtlely shifted too.  Had I put a docstring in that method I might be able to give a clearer answer there (_tuts at self_).

**Comment by ghickman** [comment]
Looking through this code again I realised we don't need to check acked/unacked.  We can have 0 unacked jobs but still be in a position where job-runner is unable to talk to job-server (as we saw yesterday with the bug fixed in #345), so I think we can rely on "has not been seen in N minutes" as a more reliable trigger for the warning banners.
