### ISSUE TITLE
Surface job `updated_at` timestamp somehow in UI

### ISSUE THREAD

**Issue by evansd** [opensafely/job-server#344]
The job-runner sets the `updated_at` timestamp each time it changes the status of a job, and will update it roughly once a minute afterwards to confirm that the job is still in the same state.

This gives us a way of confirming whether a job is actually still running (or pending) or whether something has gone wrong and we're looking at stale information.

At the most basic level we could include this timestamp alongside the other timestamps we show.

We could also have some kind of visual indication if this is too far in the past.

Note that we need to be a bit careful about what "too far" means here because while the job-runner is busy copying big files about it won't update the timestamps. This is less of a problem now that we're running natively and things are faster, but I think we'd want to leave at least five minutes before displaying any kind of warning.

**Comment by ghickman** [comment]
@evansd – I don't have much sense on what a reasonable timeout is here.  The backend check is 5 minutes, would that be too short for slow copies?

**Comment by evansd** [comment]
Just eyeballing the logs with `grep -E '(Preparing|Started)' < /e/job-runner/service.err.log` I can see a few jobs with 15 minutes worth of file-copying. I'd be inclined to set it to something conservative like 30 minutes for now.
