### ISSUE TITLE
Provide Options for Adding Jobs

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-server#61]
When adding a Job we currently provide free text fields for some options which should be derived from the Workspace's `project.yml` config.

The view will need to find, load, and parse the relevant `project.yml` to do this.

Two example configs:
* https://github.com/opensafely/households-research/blob/master/project.yaml
* https://github.com/opensafely/carehomes-research/blob/master/project.yaml

Job Runner's YAML parsing function is [here](https://github.com/opensafely/job-runner/blob/5893b48c275afd06cb016ddd52f308fbc9523668/jobrunner/project.py#L270-L345).

**Comment by sebbacon** [comment]
I had a thought about this, which we could discuss: the UI for adding a new job could potentially be a rendering of the whole project with buttons next to jobs.

So when you click a job with dependencies it indicates which other jobs would be run by you triggering that.
