### ISSUE TITLE
Wrong status icon for success

### ISSUE THREAD

**Issue by sebbacon** [opensafely/job-server#68]
![image](https://user-images.githubusercontent.com/211271/94896802-43874780-0486-11eb-9a23-cc7791af3c8d.png)

Not expected a red cross on the top two

**Comment by ghickman** [comment]
The [status parsing](https://github.com/opensafely/job-server/blob/master/jobserver/models.py#L106-L123) thinks these jobs ([97](https://jobs.opensafely.org/jobs/97/), [98](https://jobs.opensafely.org/jobs/98/), & [99](https://jobs.opensafely.org/jobs/99/)) all `Failed`.

Any idea where I'm going wrong with building the status?

**Comment by sebbacon** [comment]
Sorry, out of date with these particular examples; but just to say I think status icons are still wrong in various ways, e.g.

![image](https://user-images.githubusercontent.com/211271/97027499-bac66d80-1552-11eb-9fac-dea0ed0d7779.png)

**Comment by ghickman** [comment]
These now appear fixed 🎉

https://jobs.opensafely.org/jobs/462/
