### ISSUE TITLE
Define Statuses

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-server#83]
[There's](https://github.com/opensafely/job-server/pull/81#discussion_r499582906) [some](https://github.com/opensafely/job-server/pull/81#discussion_r499585067) [confusion](https://github.com/opensafely/job-server/pull/81#discussion_r499586852) around statuses the runner can produce and, in particular, what those should be translated to for display in the UI/filtering.

The runner defines these [status](https://github.com/opensafely/job-runner/blob/5893b48c275afd06cb016ddd52f308fbc9523668/jobrunner/exceptions.py#L27-L60) codes.

A second layer to this, we group `Job`s by `JobRequest`.  So, we also need to define how we generate the status for a `JobRequest` from its `Job`s.

Currently `Job`s can have the following statuses:
* `Completed`
* `Dependency Failed`
* `Failed`
* `Pending`
* `Running`

And `JobRequest`s can have:
* `Completed`
* `Failed`
* `Pending`
* `Running`

---

#### Job Error Code
| Runner | UI |
| ---------------------------- | ------------------- |
| `DockerError (1)`            | `Failed`            |
| `DockerRunError (2)`         | `Failed`            |
| `RepoNotFound (3)`           | `Failed`            |
| `InvalidRepo (4)`            | `Failed`            |
| `GitCloneError (5)`          | `Failed`            |
| `DependencyNotFinished (6)`  | `Pending`           |
| `DependencyFailed (7)`       | `Dependency Failed` |
| `DependencyRunning (8)`      | `Pending`           |
| `ProjectValidationError (9)` | `Failed`            |
| ???                          | `In Progress`       |
| ???                          | `Completed`         |

#### Job State
| State                      | UI                  |
| -------------------------- | ------------------- |
| `Pending`                  | `Pending`           |
| `Acked`                    | `Pending`           |
| `Cloning Repo`             | `Running`           |
| `Failed Clone`             | `Failed`            |
| `Validating Project`       | `Running`           |
| `Failed Validation`        | `Failed`            |
| `Checking Dependencies`    | `Running`           |
| `Failed Dependencies`      | `Dependency Failed` |
| `Awaiting Dependency`      | `Running`           |
| `Checking Prior Outputs`   | `Running`           |
| `Checking Existing Runner` | `Running`           |
| `Copying Required Inputs`  | `Running`           |
| `Running`                  | `Running`           |
| `Failed Action`            | `Failed`            |
| `Zombie`                   | `Failed`            |
| `Copying Expected Outputs` | `Running`           |
| `Succeeded`                | `Compelted`         |
| `Failed Missing Outputs`   | `Failed`            |

#### JobRequest Status
| Jobs | UI  |
| ------------- | ------------- |
| `Pending` | `Pending` |
| `Running` | `Running` |
| `Succeeded` | `Completed` |
| `Running with Failures` | `Running` |
| `Failed` | `Failed` |

cc @sebbacon @evansd

**Comment by sebbacon** [comment]
Here is a first pass at a state machine for more-or-less how it works at a job level at the moment (very much work in progress). Red states are different failure states; dark green states are different running states; black states are different pending states. 

![graph](https://user-images.githubusercontent.com/211271/95179300-59fc0e80-07b8-11eb-8097-082c6fd62bb0.png)

**Comment by sebbacon** [comment]
And how I think it should work at group level:

![graph-group](https://user-images.githubusercontent.com/211271/95180409-d8a57b80-07b9-11eb-9dbd-2ccf89b25e6d.png)

**Comment by ghickman** [comment]
@sebbacon – I've converted the nodes from both diagrams into statuses via the conversion tables, could you take a look and edit any you think are wrong?

Relatedly, do we want to expose more intermediary states in the UI?  I've used the free Font Awesome icons with colours to represent them so far, their library is very large so I'm sure we could find icons for other states.

**Comment by ghickman** [comment]
It's just occurred to me while working on #87 that we need to define the difference between `finished`/`completed`, `succeeded`, and `failed` in both the UI-backend and the UI itself for filtering/icons, etc.

In terms of painting the bikeshed I'm leaning towards `finished` instead of `completed` since the latter suggests a positive spin on things, whereas we want to represent "all jobs that could be run have done so".

**Comment by ghickman** [comment]
#180 is expected to cover these in job-server.

@evansd – this issue could be of use for you making the status FSM in job-runner?

I'll close for now, feel free to reopen!
