### ISSUE TITLE
Set up PAT

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-server#91]
Rather than get access to every repo a User has access to via the OAuth `repo` scope or make researchers jump through the select-each-repo-you-care-about flow of GitHub Apps lets configure a single PAT with the right scopes.

We'll need the `repo` scope to read code within a repo so the user which owns this token should probably be a new one, and behind 2FA.

The `repo` scope also gives access to list repos of a Team so we should be able to keep the token limited to just that scope.

**Comment by bloodearnest** [comment]
So, I think where we are with this as that a PAT won't work, as it has the same wide-open access that the oauth app approach did - the PAT would grant access to all of the PAT's user's orgs.

George was going to file a support ticket to ask how to get a credential that allows OpenSAFELY org only read access to private repos.

A final alternative would be to create a new user in OpenSAFELY, and give them read-access to all the study repos, and use that account to generate a PAT or an oauth token to use in job-server.

**Comment by ghickman** [comment]
I'm chatting with support on what they think the best approach is for this.  My gut feeling is we'll end up with the final alternative @bloodearnest suggested, but I'll let the support request play out to see if there's something we've missed.

**Comment by ghickman** [comment]
Support are saying we can get what we want with a GitHub App:

>> To answer both of these: we'd like an admin of the OpenSAFELY Org to be able to generate a secret token (much like a PAT but for the Org, rather than a User), which we'd use as the Auth token to access the API from our App.

> This is currently possible with GitHub Apps. After you install a GitHub App on the OpenSAFELY Org (this step of installing needs to be performed by a human, but happens only once), you can create an token for that installation:

> https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-an-installation

> If at the installation step the admin installed the App on all repositories owned by the organization, then the App will have access to all current and future repositories of the organization.

> When you create an installation token, you can specify which subset of repositories the token will have access to.

Which suggests I should tackle #89 soon.

**Comment by bloodearnest** [comment]
Hmm, so if our options are a) specific repos or b) all repos, that is not great either. If we do a), and reading the link they provided, it looks like we would need to re-install the app each time we added a new study repo? If we do b), it gives it access to the private infra repos.

Can the App be restricted to read-only on the repos? Is that a separate set of permission we grant at install time? If so, b) might be acceptable. But also means it could read any secrets in any repos too (which we are talking about doing, e.g. generic docker RO login and stata license stuff).

We have created the [RO service account](https://github.com/ebmdatalab/sysadmin/issues/107) now as it was needed for other purposes. This gives us control of both org scope and permissions, albeit a bit hamfistedly, but I wonder if we should just go ahead with that for now rather than wrestle with app auth/perms?

**Comment by ghickman** [comment]
> Can the App be restricted to read-only on the repos?

I think that's the salient question for GitHub App vs RO Service Account.  If we can't do that then any bug in job-server's repo filtering code could open up secrets.

I'll see if that's possible with a GitHub App and timebound my spike to avoid sinking more time into this issue!

**Comment by ghickman** [comment]
Ok so I had a play at getting a GitHub App set up, time bounded to 30 minutes since I've done quite a bit with the GitHub API before so my theory was It Shouldn't Be That Hard™.

Narrator: it was.

Python Social Auth supports GitHub Apps but it wasn't immediately obvious how we'd handle their GitHubOAuth and GitHubApp backends inside the application.  It's definitely possible (I've done it with GitHubOAuth and GitHubEnterprise before), but I think there would be a lot of work to make sure we produce multiple callback endpoints and to make sure the flows don't overlap since we don't want to use the GitHub App for User auth.

From reading more of the docs, I think a GitHub App is probably still the Correct™ way to handle this flow, if only because it's the expected way to have Bot users.

That being said I think the RO Service Account is the pragmatic solution here and I'll move forward with that.

Thanks for your help working through and getting the RO Service Account set up @bloodearnest!
